"""empty message

Revision ID: f83ce8e18ac2
Revises: d43829c63791
Create Date: 2025-04-12 19:29:52.444357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83ce8e18ac2'
down_revision: Union[str, None] = 'd43829c63791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_questions', sa.Column('score', sa.Integer(), nullable=False))
    op.drop_column('games', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('game_questions', 'score')
    # ### end Alembic commands ###
